### PR TITLE
Tweakable terminationGracePeriodSeconds, liveness/readiness probes

### PR DESCRIPTION
**Pull request by damdo**
Add ability to tweak terminationGracePeriodSeconds and liveness/readiness probes.

### CODE REVIEW

**Comment by damdo** [comment]
cc. @dirien when you have time to take a look :) Thanks

**Comment by damdo** [comment]
I've also included tweakability for terminationGracePeriodSeconds.

**Review by dirien — APPROVED** [review]
Hey @damdo,

thanks for the PR. Looks good for me!

**Comment by damdo** [comment]
Thanks!

**Pull request merged**
