### PR TITLE
Support to specify a certain version for extra node modules instead of latest every time

### PR DESCRIPTION
**Pull request by mgreg89**
### Thank you for making `node-red ⚙` better

This PR is adding optional support for versions within extra node modules, such that you don't have to always install the latest module.

*Also verify you have:*

* [x] Read the [contributions](../CONTRIBUTING.md) page.
* [x] Read the [DCO](../DCO), if you are a first time contributor.
* [x] Read the [code of conduct]([Code of Conduct] (https://github.com/SchwarzIT/.github/blob/main/CODE_OF_CONDUCT.md)).

### CODE REVIEW

**Comment by dirien** [comment]
Hey @mgreg89,

can you please sign the commit with `git commit --amend --signoff`

**Comment by dirien** [comment]
@mgreg89 have a look again please.

**Comment by mgreg89** [comment]
Sorry, I haven't worked with signed off commits before, but it should be fine now

**Comment by dirien** [comment]
@mgreg89, thanks for your contribution

**Pull request merged**
